apiVersion: batch/v1
kind: CronJob
metadata:
  name: vici-backup
spec:
  schedule: "0 0 * * *"  # Run at midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:13
            command:
            - /bin/bash
            - /scripts/backup.sh
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
            - name: backup-scripts
              mountPath: /scripts
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc
          - name: backup-scripts
            configMap:
              name: backup-scripts
          restartPolicy: OnFailure 