apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: rest
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: inter-node
  selector:
    app: elasticsearch 