apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: "vici-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.monitoring.enabled: true
    xpack.watcher.enabled: true
    xpack.ml.enabled: true
    xpack.graph.enabled: true
    xpack.reporting.enabled: true
    xpack.security.audit.enabled: true
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false 