apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
type: Opaque
data:
  # This is a base64 encoded password - replace with your actual encoded password
  admin-password: YWRtaW4xMjM=  # admin123 