apiVersion: apps/v1
kind: Deployment
metadata:
  name: vici-app
  labels:
    app: vici
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vici
  template:
    metadata:
      labels:
        app: vici
    spec:
      containers:
      - name: vici-app
        image: vici-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: vici-config
              key: postgres_host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: vici-config
              key: postgres_port
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: vici-config
              key: postgres_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: vici-secrets
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vici-secrets
              key: postgres_password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: vici-config
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: vici-config
              key: redis_port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vici-secrets
              key: redis_password
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 