apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: vici
    component: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: vici
    component: database 