apiVersion: v1
kind: Service
metadata:
  name: vici-app
  labels:
    app: vici
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: vici 